---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: gpu-dsp
spec:
  selector:
    matchLabels:
      name: dcgm-exporter
  template:
    metadata:
      labels:
        name: dcgm-exporter
    spec:
      containers:
        - name: dcgm-exporter
          image: nvcr.io/nvidia/k8s/dcgm-exporter:3.3.5-3.1.7-ubuntu20.04
          ports:
            - containerPort: 9400
          resources:
            limits:
              nvidia.com/gpu: 1
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-grafana-dashboard
  namespace: gpu-dsp
  labels:
    grafana_dashboard: "1"
data:
  gpu-dashboard.json: |
    {
      "id": null,
      "uid": "gpu-monitoring",
      "title": "NVIDIA GPU Monitoring",
      "tags": [
        "gpu",
        "nvidia",
        "dcgm"
      ],
      "timezone": "browser",
      "schemaVersion": 26,
      "version": 1,
      "refresh": "10s",
      "panels": [
        {
          "type": "graph",
          "title": "GPU Utilization (%)",
          "targets": [
            {
              "expr": "DCGM_FI_DEV_GPU_UTIL",
              "legendFormat": "GPU {{pod}}",
              "interval": ""
            }
          ],
          "datasource": "Prometheus",
          "gridPos": {
            "x": 0,
            "y": 0,
            "w": 12,
            "h": 8
          }
        },
        {
          "type": "graph",
          "title": "Memory Usage (MiB)",
          "targets": [
            {
              "expr": "DCGM_FI_DEV_FB_USED / 1024 / 1024",
              "legendFormat": "GPU {{pod}}",
              "interval": ""
            }
          ],
          "datasource": "Prometheus",
          "gridPos": {
            "x": 12,
            "y": 0,
            "w": 12,
            "h": 8
          }
        },
        {
          "type": "graph",
          "title": "GPU Temperature (C)",
          "targets": [
            {
              "expr": "DCGM_FI_DEV_GPU_TEMP",
              "legendFormat": "GPU {{pod}}",
              "interval": ""
            }
          ],
          "datasource": "Prometheus",
          "gridPos": {
            "x": 0,
            "y": 9,
            "w": 24,
            "h": 8
          }
        }
      ]
    }